### PR TITLE
Add how to for getting a kubernetes robot token

### PR DESCRIPTION
**Pull request by tasharnvb**
Btw the change on local_certs.md was a change to its permissions since it was executable before.

### CODE REVIEW

**Comment by oyelekci** [comment]
Do we not also need instructions for people creating the tokens? i.e. smth like https://github.com/UKHomeOffice/application-container-platform/blob/master/how-to-docs/artifact-robot.md but for the new cluster?

**Comment by tasharnvb** [comment]
As I understood it this doc is only for users, i.e. the people who want the token

**Comment by Joseph-Irving** [comment]
@oyelekci this is just from a user perspective. Though we could have a separate doc with those instructions for us

**Comment by oyelekci** [comment]
@tasharnvb A separate doc with instructions for devops staff would be helpful. Please take that one as your next task. This one looks good, thanks.

**Comment by jits** [comment]
We just need to remember to actually create this support request template on the prod version of the hub :) (and when we do we can link to it directly in this doc)

**Pull request merged**
