### PR TITLE
Remove references to drone.yml signing

### PR DESCRIPTION
**Pull request by asmith030**

### CODE REVIEW

**Comment by jits** [comment]
Maybe add a `Migrating start a DSP Drone to ACP Drone section` and add a note there that the sig file can be deleted?

**Comment by tasharnvb** [comment]
We will do a `Migrating to ACP Drone` section as a separate pull request

**Comment by jits** [comment]
@tasharnvb – sounds good 👍 

LGTM

**Comment by tasharnvb** [comment]
LGTM

**Pull request merged**
