### PR TITLE
Making a single page, and updating + use readthedocs

### PR DESCRIPTION
**Pull request by jaykeshur**

### CODE REVIEW

**Comment by jon-shanks** [comment]
it might be worth creating jekyl and a decent theme and moving this to github pages really

**Comment by jits** [comment]
@jon-shanks – +1

Note: 
- In this case, probably best to have the whole GitHub Pages site at the root of the repo (in `master`) as opposed to in `docs`, since there's nothing else in this repo.
- The `cayman` theme is designed mainly for single page sites where you download something (e.g. a software module) – it's not easy to have multiple pages (though not impossible) – there are some docs-oriented themes here: https://jekyllthemes.io/jekyll-documentation-themes

If you select a theme, I can move all of the docs here to a GitHub Pages site?

**Comment by jon-shanks** [comment]
Fair point, i think the just-the-docs looks good to me

**Comment by jits** [comment]
@jon-shanks – 👍 

@jaykeshur – should we get these changes merged, then I can set up the GitHub Pages bit? Do you want to go with the single file approach, or break down into multiple pages? (the template Jon picked out has a decent way of organising multiple pages, and also supports search).

**Comment by marcinc** [comment]
Maybe we can just use what we already use for docs in some of the projects? `mkdocs` specifically... but not fussed either way.

**Comment by jaykeshur** [comment]
updated to use mkdocs, did use just-the-docs first, but wasn't as nice to use

**Comment by jaykeshur** [comment]
Its here: http://ukhomeoffice.github.io/application-container-platform/

**Pull request merged**
